# Generated by Django 5.0.2 on 2024-02-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerorganization',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('approve', 'Approve'), ('reject', 'Reject'), ('allocated', 'Allocated')], default='in_progress', max_length=50),
        ),
    ]
