# Generated by Django 5.0.2 on 2024-03-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_buyerorganization_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerorganization',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyerorganization',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyerorganization',
            name='status',
            field=models.CharField(choices=[('in_progress', 'InProgress'), ('approve', 'Approve'), ('reject', 'Reject'), ('allocated', 'Allocated')], default='in_progress', max_length=50),
        ),
    ]
