# Generated by Django 5.0.2 on 2024-04-12 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_buyerorganization_is_paid_buyerorganization_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerorganization',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
