# Generated by Django 5.0.2 on 2024-04-26 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_buyerorganization_create_date'),
        ('space', '0008_remove_workspace_spacecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'InProgress'), ('approve', 'Approve'), ('reject', 'Reject'), ('allocated', 'Allocated')], default='in_progress', max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('Workspace_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_workspace', to='space.workspace')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_workspace_image', to='space.workspaceimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
