# Generated by Django 5.0.2 on 2024-02-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_alter_workspaceimage_workspace_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
