# Generated by Django 5.0.2 on 2024-04-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_workspace_city_workspace_country_workspace_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='SpaceCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.spacecategory'),
        ),
        migrations.AlterField(
            model_name='spacecategory',
            name='name',
            field=models.CharField(choices=[('Office_Desk', 'Office_Desk'), ('Conference Room', 'Conference Room'), ('Front Office', 'Front Office')], max_length=50),
        ),
    ]
