# Generated by Django 5.0.2 on 2024-04-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_workspace_spacecategory_alter_spacecategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='SpaceCategory',
        ),
        migrations.AddField(
            model_name='workspace',
            name='spacecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_category_name', to='space.spacecategory'),
        ),
    ]
